### ISSUE TITLE
INSTALL.md should have install instructions

### ISSUE THREAD

**Issue by Croydon** [nil0x42/phpsploit#106]
I mean I can `assume` that I need to do a `pip install` and that's it, but I don't know that.

Please add actual install steps to INSTALL.md 😄

**Comment by nil0x42** [comment]
added a "Quick Start" category on INSTALL.md ( e0b818dc645cd6f0f21bd5d8ccc9702de3166a31 ) thank you for reporting !

**Comment by nil0x42** [comment]
feel free to re-open
