### ISSUE TITLE
a window shell trate mysql data

### ISSUE THREAD

**Issue by zhanghang25** [nil0x42/phpsploit#119]

**Comment by zhanghang25** [comment]
phpsploit(www.hualanbio.com) > mysql mysqldump -u hualanbiocom -p 2dZDcQUW92znC6fz -d test > d:/cc.sql;
[-] mysql: ERROR: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysqldump -u hualanbiocom -p 2dZDcQUW92znC6fz -d test' at line 1
phpsploit(www.hualanbio.com) >

**Comment by nil0x42** [comment]
@zhanghang25 the mysql plugin is a php/python based reimplementation of the original mysql command.
Therefore, arguments are interpreted as an SQL query, using php built-in mysql_*() functions, without touching any binary on the system.

Currently, phpsploit have no mysqldump plugin.
But if you want, you can still use the remote system's `mysqldump` command (if available).

To run remote binaries, use the `run` plugin (`help run`)

Also, i invite you to always use `help <COMMAND>` to read more about the sacope of phpsploit commands.

Anyway, thank you for posting the issue :)

**Comment by nil0x42** [comment]
Please close the issue if you consider it resolved

**Comment by nil0x42** [comment]
Closing after ~4 months.
Feel free to re-open if the issue persists
