### ISSUE TITLE
socks5 proxy not working

### ISSUE THREAD

**Issue by wicked** [nil0x42/phpsploit#194]
Configuration settings loaded from previous session has PROXY set to socks5, with tor service not enabled and not yet started. 

On run phpsploit still sends the payload to target without checking if it is using the proxy and successfully connects without proxy.

```
set PROXY socks5://127.0.0.1:9050

[*] Shell obtained by PHP (MY_IP -> TARGET_IP)
```

I have checked on the target server and it also connects as MY_IP without using the socks5 proxy.

Test service while using curl socks5 proxy works just fine with torrc my configuration

```
$ sudo systemctl stop tor
$ curl --socks5 127.0.0.1:9050 'https://ipinfo.io/ip'
curl: (7) Failed to connect to 127.0.0.1 port 9050 after 0 ms: Couldn't connect to server
$ sudo systemctl start tor
$ curl --socks5 127.0.0.1:9050 'https://ipinfo.io/ip'
TOR_IP
```

**Comment by nil0x42** [comment]
fixed by https://github.com/nil0x42/phpsploit/commit/4710549370d3ba509eb1008b32703dab262b636e

please pull latest commits from master, and close the issue if you confirme the issue has been fixed on your side

**Comment by wicked** [comment]
Pulled latest commit 43093c6 on master branch. 

On new session, I tried setting using every proxy scheme. `set PROXY` does not work. 

I tried reverting to the recent last commit that `set PROXY` still works only up to 962d32d.

**Comment by nil0x42** [comment]
Okay, i'm about to push a fix for this. But from what i can see, it's just a display bug (PROXY displays as None, while in reality it is active). So if you set PROXY, it should work, even though it show itself as None

**Comment by wicked** [comment]
All working fine here. Thank you for the fixes!

**Comment by nil0x42** [comment]
Nice !
