### ISSUE TITLE
Private proxy

### ISSUE THREAD

**Issue by suvarivaza** [nil0x42/phpsploit#209]
Hi
I can’t find information on how to use private proxies that require setting a login and password

**Comment by nil0x42** [comment]
Hi ! It's not actually implemented. You can implement it by patching src/datatypes/Proxy.py
Otherwise i'll consider doing it when i'll have time

**Comment by nil0x42** [comment]
you can also use glider or some other proxy forwarder.
for example, glider listens on localhost & serves a credentials-free proxy locally, which forwards to your proxy with credentials.
