### ISSUE TITLE
'corectl reload-plugins'

### ISSUE THREAD

**Issue by champrohan123** [nil0x42/phpsploit#30]
after executing ./phpsploit it shows this error

Plugin loader: 2 error(s) found (use `corectl reload-plugins` for more infos)
#] Couldn't compile plugin: « /opt/phpsploit/plugins/file_system/fileinfo »
[#] Traceback (most recent call last):
[#]   File "/opt/phpsploit/src/core/plugins/Plugin.py", line 56, in __init__
[#]     code = compile(script, "", "exec")
[#]   File "<string>", line 69
[#]     print ''
[#]            ^
[#] SyntaxError: Missing parentheses in call to 'print'
[#] 
[#] Couldn't compile plugin: « /opt/phpsploit/plugins/file_system/search »
[#] Traceback (most recent call last):
[#]   File "/opt/phpsploit/src/core/plugins/Plugin.py", line 56, in __init__
[#]     code = compile(script, "", "exec")
[#]   File "<string>", line 56
[#]     print ''
[#]            ^
[#] SyntaxError: Missing parentheses in call to 'print'
![screenshot 5](https://cloud.githubusercontent.com/assets/16543074/12093972/fe2b3a26-b32b-11e5-8049-5ed02b4a1475.png)

**Comment by nil0x42** [comment]
2 years ago, i completely rewritten phpsploit for python3, and changed the plugins API, and had laziness on rewritting those two plugins.
you can use the framework normally, but still not use those two plugins.

Me, or any other contributor needs to rewrite theses plugins soon..

**Comment by nil0x42** [comment]
Update: fileinfo plugin has been fully rewritten en renamed to `stat`

**Comment by nil0x42** [comment]
resolved by commit a7dd8ba84b25496362fca4511ce2254da44cf719

**Comment by nil0x42** [comment]
@all-contributors, please add @rohantarai for reporting bug
