### ISSUE TITLE
post parameter for target

### ISSUE THREAD

**Issue by sohelzerdoumi** [nil0x42/phpsploit#47]
Hi,
Is it possible to define some post parameters for a target?
We can only define as POST HTTP method, but without any extra parameters.

ex:
POST http://target.com/
DATA: action=vulnerable

**Comment by nil0x42** [comment]
just fixed in 7e084537c01d4e38ddd7b7868aa6ce6feb4b55aa .
Happy hacking :)

**Comment by sohelzerdoumi** [comment]
So fast, thx men ;)

**Comment by nil0x42** [comment]
@all-contributors, please add @sohelzerdoumi for bug reporting (missing feature)

**Comment by sohelzerdoumi** [comment]
ahah thx :)
