### ISSUE TITLE
Changes in data/config/config not loaded

### ISSUE THREAD

**Issue by mrunc** [nil0x42/phpsploit#49]
Are you sure chnages in data/config/config is sourced and applied after running phpsploit

I changed and uncommented the PASSKEY and but I don't see any change in set command output

This is on macOS - Python3

**Comment by mrunc** [comment]
Looks like I have to add it as an option now it's working fine

    alias phpsploit="python3 ~/phpsploit/phpsploit -c ~/phpsploit/data/config/config"

**Comment by nil0x42** [comment]
Hi, the config file you just aliased should not to be modified, but provides a set of default values for current version.
The first time you run phpsploit, it creates a user configuration directory in one of the following locations:
~/.config/phpsploit/
OR
~/.phpsploit/
